In [ ]:
import pandas as pd
import numpy as np

## 1. Data Loading

In [2]:
calendar = pd.read_csv("../data/raw/calendar.csv")

sales_validation = pd.read_csv(
    "../data/raw/sales_train_validation.csv"
)

sales_evaluation = pd.read_csv(
    "../data/raw/sales_train_evaluation.csv"
)

sell_prices = pd.read_csv(
    "../data/raw/sell_prices.csv"
)

## 2. Dataset Structure

### Shape

In [4]:
datasets = {
    "calendar": calendar,
    "sales_validation": sales_validation,
    "sales_evaluation": sales_evaluation,
    "sell_prices": sell_prices
}

for name, df in datasets.items():
    print(f"---------------- {name} ----------------")
    print(f"Number of Rows: {df.shape[0]}")
    print(f"Number of Columns: {df.shape[1]}")
    print("Columns")
    print(df.columns.to_list())
    print()

---------------- calendar ----------------
Number of Rows: 1969
Number of Columns: 14
Columns
['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

---------------- sales_validation ----------------
Number of Rows: 30490
Number of Columns: 1919
Columns
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10', 'd_11', 'd_12', 'd_13', 'd_14', 'd_15', 'd_16', 'd_17', 'd_18', 'd_19', 'd_20', 'd_21', 'd_22', 'd_23', 'd_24', 'd_25', 'd_26', 'd_27', 'd_28', 'd_29', 'd_30', 'd_31', 'd_32', 'd_33', 'd_34', 'd_35', 'd_36', 'd_37', 'd_38', 'd_39', 'd_40', 'd_41', 'd_42', 'd_43', 'd_44', 'd_45', 'd_46', 'd_47', 'd_48', 'd_49', 'd_50', 'd_51', 'd_52', 'd_53', 'd_54', 'd_55', 'd_56', 'd_57', 'd_58', 'd_59', 'd_60', 'd_61', 'd_62', 'd_63', 'd_64', 'd_65', 'd_66', 'd_67', 'd_68', 'd_69', 'd_70', 'd_71', 'd_72', 'd_73', 'd_74', 'd_75', 'd_76', 'd_77', 'd_78', 'd_79', 'd_80', 'd_81', 'd_82', 'd_83', 'd_84', 'd_85', 'd_86', 'd_87', 'd_88', 'd_89', 'd_90', 'd_91', 'd_92', 'd_93', 'd_94', 'd_95', 'd_96', 'd_97', 'd_98', 'd_99', 'd_100', 'd_101', 'd_102', 'd_103', 'd_104', 'd_105', 'd_106', 'd_107', 'd_108', 'd_109', 'd_110', 'd_111', 'd_112', 'd_113', 'd_114', 'd_115', 'd_116', 'd_117', 'd_118', 'd_119', 'd_120', 'd_121', 'd_122', 'd_123', 'd_124', 'd_125', 'd_126', 'd_127', 'd_128', 'd_129', 'd_130', 'd_131', 'd_132', 'd_133', 'd_134', 'd_135', 'd_136', 'd_137', 'd_138', 'd_139', 'd_140', 'd_141', 'd_142', 'd_143', 'd_144', 'd_145', 'd_146', 'd_147', 'd_148', 'd_149', 'd_150', 'd_151', 'd_152', 'd_153', 'd_154', 'd_155', 'd_156', 'd_157', 'd_158', 'd_159', 'd_160', 'd_161', 'd_162', 'd_163', 'd_164', 'd_165', 'd_166', 'd_167', 'd_168', 'd_169', 'd_170', 'd_171', 'd_172', 'd_173', 'd_174', 'd_175', 'd_176', 'd_177', 'd_178', 'd_179', 'd_180', 'd_181', 'd_182', 'd_183', 'd_184', 'd_185', 'd_186', 'd_187', 'd_188', 'd_189', 'd_190', 'd_191', 'd_192', 'd_193', 'd_194', 'd_195', 'd_196', 'd_197', 'd_198', 'd_199', 'd_200', 'd_201', 'd_202', 'd_203', 'd_204', 'd_205', 'd_206', 'd_207', 'd_208', 'd_209', 'd_210', 'd_211', 'd_212', 'd_213', 'd_214', 'd_215', 'd_216', 'd_217', 'd_218', 'd_219', 'd_220', 'd_221', 'd_222', 'd_223', 'd_224', 'd_225', 'd_226', 'd_227', 'd_228', 'd_229', 'd_230', 'd_231', 'd_232', 'd_233', 'd_234', 'd_235', 'd_236', 'd_237', 'd_238', 'd_239', 'd_240', 'd_241', 'd_242', 'd_243', 'd_244', 'd_245', 'd_246', 'd_247', 'd_248', 'd_249', 'd_250', 'd_251', 'd_252', 'd_253', 'd_254', 'd_255', 'd_256', 'd_257', 'd_258', 'd_259', 'd_260', 'd_261', 'd_262', 'd_263', 'd_264', 'd_265', 'd_266', 'd_267', 'd_268', 'd_269', 'd_270', 'd_271', 'd_272', 'd_273', 'd_274', 'd_275', 'd_276', 'd_277', 'd_278', 'd_279', 'd_280', 'd_281', 'd_282', 'd_283', 'd_284', 'd_285', 'd_286', 'd_287', 'd_288', 'd_289', 'd_290', 'd_291', 'd_292', 'd_293', 'd_294', 'd_295', 'd_296', 'd_297', 'd_298', 'd_299', 'd_300', 'd_301', 'd_302', 'd_303', 'd_304', 'd_305', 'd_306', 'd_307', 'd_308', 'd_309', 'd_310', 'd_311', 'd_312', 'd_313', 'd_314', 'd_315', 'd_316', 'd_317', 'd_318', 'd_319', 'd_320', 'd_321', 'd_322', 'd_323', 'd_324', 'd_325', 'd_326', 'd_327', 'd_328', 'd_329', 'd_330', 'd_331', 'd_332', 'd_333', 'd_334', 'd_335', 'd_336', 'd_337', 'd_338', 'd_339', 'd_340', 'd_341', 'd_342', 'd_343', 'd_344', 'd_345', 'd_346', 'd_347', 'd_348', 'd_349', 'd_350', 'd_351', 'd_352', 'd_353', 'd_354', 'd_355', 'd_356', 'd_357', 'd_358', 'd_359', 'd_360', 'd_361', 'd_362', 'd_363', 'd_364', 'd_365', 'd_366', 'd_367', 'd_368', 'd_369', 'd_370', 'd_371', 'd_372', 'd_373', 'd_374', 'd_375', 'd_376', 'd_377', 'd_378', 'd_379', 'd_380', 'd_381', 'd_382', 'd_383', 'd_384', 'd_385', 'd_386', 'd_387', 'd_388', 'd_389', 'd_390', 'd_391', 'd_392', 'd_393', 'd_394', 'd_395', 'd_396', 'd_397', 'd_398', 'd_399', 'd_400', 'd_401', 'd_402', 'd_403', 'd_404', 'd_405', 'd_406', 'd_407', 'd_408', 'd_409', 'd_410', 'd_411', 'd_412', 'd_413', 'd_414', 'd_415', 'd_416', 'd_417', 'd_418', 'd_419', 'd_420', 'd_421', 'd_422', 'd_423', 'd_424', 'd_425', 'd_426', 'd_427', 'd_428', 'd_429', 'd_430', 'd_431', 'd_432', 'd_433', 'd_434', 'd_435', 'd_436', 'd_437', 'd_438', 'd_439', 'd_440', 'd_441', 'd_442', 'd_443', 'd_444', 'd_445', 'd_446', 'd_447', 'd_448', 'd_449', 'd_450', 'd_451', 'd_452', 'd_453', 'd_454', 'd_455', 'd_456', 'd_457', 'd_458', 'd_459', 'd_460', 'd_461', 'd_462', 'd_463', 'd_464', 'd_465', 'd_466', 'd_467', 'd_468', 'd_469', 'd_470', 'd_471', 'd_472', 'd_473', 'd_474', 'd_475', 'd_476', 'd_477', 'd_478', 'd_479', 'd_480', 'd_481', 'd_482', 'd_483', 'd_484', 'd_485', 'd_486', 'd_487', 'd_488', 'd_489', 'd_490', 'd_491', 'd_492', 'd_493', 'd_494', 'd_495', 'd_496', 'd_497', 'd_498', 'd_499', 'd_500', 'd_501', 'd_502', 'd_503', 'd_504', 'd_505', 'd_506', 'd_507', 'd_508', 'd_509', 'd_510', 'd_511', 'd_512', 'd_513', 'd_514', 'd_515', 'd_516', 'd_517', 'd_518', 'd_519', 'd_520', 'd_521', 'd_522', 'd_523', 'd_524', 'd_525', 'd_526', 'd_527', 'd_528', 'd_529', 'd_530', 'd_531', 'd_532', 'd_533', 'd_534', 'd_535', 'd_536', 'd_537', 'd_538', 'd_539', 'd_540', 'd_541', 'd_542', 'd_543', 'd_544', 'd_545', 'd_546', 'd_547', 'd_548', 'd_549', 'd_550', 'd_551', 'd_552', 'd_553', 'd_554', 'd_555', 'd_556', 'd_557', 'd_558', 'd_559', 'd_560', 'd_561', 'd_562', 'd_563', 'd_564', 'd_565', 'd_566', 'd_567', 'd_568', 'd_569', 'd_570', 'd_571', 'd_572', 'd_573', 'd_574', 'd_575', 'd_576', 'd_577', 'd_578', 'd_579', 'd_580', 'd_581', 'd_582', 'd_583', 'd_584', 'd_585', 'd_586', 'd_587', 'd_588', 'd_589', 'd_590', 'd_591', 'd_592', 'd_593', 'd_594', 'd_595', 'd_596', 'd_597', 'd_598', 'd_599', 'd_600', 'd_601', 'd_602', 'd_603', 'd_604', 'd_605', 'd_606', 'd_607', 'd_608', 'd_609', 'd_610', 'd_611', 'd_612', 'd_613', 'd_614', 'd_615', 'd_616', 'd_617', 'd_618', 'd_619', 'd_620', 'd_621', 'd_622', 'd_623', 'd_624', 'd_625', 'd_626', 'd_627', 'd_628', 'd_629', 'd_630', 'd_631', 'd_632', 'd_633', 'd_634', 'd_635', 'd_636', 'd_637', 'd_638', 'd_639', 'd_640', 'd_641', 'd_642', 'd_643', 'd_644', 'd_645', 'd_646', 'd_647', 'd_648', 'd_649', 'd_650', 'd_651', 'd_652', 'd_653', 'd_654', 'd_655', 'd_656', 'd_657', 'd_658', 'd_659', 'd_660', 'd_661', 'd_662', 'd_663', 'd_664', 'd_665', 'd_666', 'd_667', 'd_668', 'd_669', 'd_670', 'd_671', 'd_672', 'd_673', 'd_674', 'd_675', 'd_676', 'd_677', 'd_678', 'd_679', 'd_680', 'd_681', 'd_682', 'd_683', 'd_684', 'd_685', 'd_686', 'd_687', 'd_688', 'd_689', 'd_690', 'd_691', 'd_692', 'd_693', 'd_694', 'd_695', 'd_696', 'd_697', 'd_698', 'd_699', 'd_700', 'd_701', 'd_702', 'd_703', 'd_704', 'd_705', 'd_706', 'd_707', 'd_708', 'd_709', 'd_710', 'd_711', 'd_712', 'd_713', 'd_714', 'd_715', 'd_716', 'd_717', 'd_718', 'd_719', 'd_720', 'd_721', 'd_722', 'd_723', 'd_724', 'd_725', 'd_726', 'd_727', 'd_728', 'd_729', 'd_730', 'd_731', 'd_732', 'd_733', 'd_734', 'd_735', 'd_736', 'd_737', 'd_738', 'd_739', 'd_740', 'd_741', 'd_742', 'd_743', 'd_744', 'd_745', 'd_746', 'd_747', 'd_748', 'd_749', 'd_750', 'd_751', 'd_752', 'd_753', 'd_754', 'd_755', 'd_756', 'd_757', 'd_758', 'd_759', 'd_760', 'd_761', 'd_762', 'd_763', 'd_764', 'd_765', 'd_766', 'd_767', 'd_768', 'd_769', 'd_770', 'd_771', 'd_772', 'd_773', 'd_774', 'd_775', 'd_776', 'd_777', 'd_778', 'd_779', 'd_780', 'd_781', 'd_782', 'd_783', 'd_784', 'd_785', 'd_786', 'd_787', 'd_788', 'd_789', 'd_790', 'd_791', 'd_792', 'd_793', 'd_794', 'd_795', 'd_796', 'd_797', 'd_798', 'd_799', 'd_800', 'd_801', 'd_802', 'd_803', 'd_804', 'd_805', 'd_806', 'd_807', 'd_808', 'd_809', 'd_810', 'd_811', 'd_812', 'd_813', 'd_814', 'd_815', 'd_816', 'd_817', 'd_818', 'd_819', 'd_820', 'd_821', 'd_822', 'd_823', 'd_824', 'd_825', 'd_826', 'd_827', 'd_828', 'd_829', 'd_830', 'd_831', 'd_832', 'd_833', 'd_834', 'd_835', 'd_836', 'd_837', 'd_838', 'd_839', 'd_840', 'd_841', 'd_842', 'd_843', 'd_844', 'd_845', 'd_846', 'd_847', 'd_848', 'd_849', 'd_850', 'd_851', 'd_852', 'd_853', 'd_854', 'd_855', 'd_856', 'd_857', 'd_858', 'd_859', 'd_860', 'd_861', 'd_862', 'd_863', 'd_864', 'd_865', 'd_866', 'd_867', 'd_868', 'd_869', 'd_870', 'd_871', 'd_872', 'd_873', 'd_874', 'd_875', 'd_876', 'd_877', 'd_878', 'd_879', 'd_880', 'd_881', 'd_882', 'd_883', 'd_884', 'd_885', 'd_886', 'd_887', 'd_888', 'd_889', 'd_890', 'd_891', 'd_892', 'd_893', 'd_894', 'd_895', 'd_896', 'd_897', 'd_898', 'd_899', 'd_900', 'd_901', 'd_902', 'd_903', 'd_904', 'd_905', 'd_906', 'd_907', 'd_908', 'd_909', 'd_910', 'd_911', 'd_912', 'd_913', 'd_914', 'd_915', 'd_916', 'd_917', 'd_918', 'd_919', 'd_920', 'd_921', 'd_922', 'd_923', 'd_924', 'd_925', 'd_926', 'd_927', 'd_928', 'd_929', 'd_930', 'd_931', 'd_932', 'd_933', 'd_934', 'd_935', 'd_936', 'd_937', 'd_938', 'd_939', 'd_940', 'd_941', 'd_942', 'd_943', 'd_944', 'd_945', 'd_946', 'd_947', 'd_948', 'd_949', 'd_950', 'd_951', 'd_952', 'd_953', 'd_954', 'd_955', 'd_956', 'd_957', 'd_958', 'd_959', 'd_960', 'd_961', 'd_962', 'd_963', 'd_964', 'd_965', 'd_966', 'd_967', 'd_968', 'd_969', 'd_970', 'd_971', 'd_972', 'd_973', 'd_974', 'd_975', 'd_976', 'd_977', 'd_978', 'd_979', 'd_980', 'd_981', 'd_982', 'd_983', 'd_984', 'd_985', 'd_986', 'd_987', 'd_988', 'd_989', 'd_990', 'd_991', 'd_992', 'd_993', 'd_994', 'd_995', 'd_996', 'd_997', 'd_998', 'd_999', 'd_1000', 'd_1001', 'd_1002', 'd_1003', 'd_1004', 'd_1005', 'd_1006', 'd_1007', 'd_1008', 'd_1009', 'd_1010', 'd_1011', 'd_1012', 'd_1013', 'd_1014', 'd_1015', 'd_1016', 'd_1017', 'd_1018', 'd_1019', 'd_1020', 'd_1021', 'd_1022', 'd_1023', 'd_1024', 'd_1025', 'd_1026', 'd_1027', 'd_1028', 'd_1029', 'd_1030', 'd_1031', 'd_1032', 'd_1033', 'd_1034', 'd_1035', 'd_1036', 'd_1037', 'd_1038', 'd_1039', 'd_1040', 'd_1041', 'd_1042', 'd_1043', 'd_1044', 'd_1045', 'd_1046', 'd_1047', 'd_1048', 'd_1049', 'd_1050', 'd_1051', 'd_1052', 'd_1053', 'd_1054', 'd_1055', 'd_1056', 'd_1057', 'd_1058', 'd_1059', 'd_1060', 'd_1061', 'd_1062', 'd_1063', 'd_1064', 'd_1065', 'd_1066', 'd_1067', 'd_1068', 'd_1069', 'd_1070', 'd_1071', 'd_1072', 'd_1073', 'd_1074', 'd_1075', 'd_1076', 'd_1077', 'd_1078', 'd_1079', 'd_1080', 'd_1081', 'd_1082', 'd_1083', 'd_1084', 'd_1085', 'd_1086', 'd_1087', 'd_1088', 'd_1089', 'd_1090', 'd_1091', 'd_1092', 'd_1093', 'd_1094', 'd_1095', 'd_1096', 'd_1097', 'd_1098', 'd_1099', 'd_1100', 'd_1101', 'd_1102', 'd_1103', 'd_1104', 'd_1105', 'd_1106', 'd_1107', 'd_1108', 'd_1109', 'd_1110', 'd_1111', 'd_1112', 'd_1113', 'd_1114', 'd_1115', 'd_1116', 'd_1117', 'd_1118', 'd_1119', 'd_1120', 'd_1121', 'd_1122', 'd_1123', 'd_1124', 'd_1125', 'd_1126', 'd_1127', 'd_1128', 'd_1129', 'd_1130', 'd_1131', 'd_1132', 'd_1133', 'd_1134', 'd_1135', 'd_1136', 'd_1137', 'd_1138', 'd_1139', 'd_1140', 'd_1141', 'd_1142', 'd_1143', 'd_1144', 'd_1145', 'd_1146', 'd_1147', 'd_1148', 'd_1149', 'd_1150', 'd_1151', 'd_1152', 'd_1153', 'd_1154', 'd_1155', 'd_1156', 'd_1157', 'd_1158', 'd_1159', 'd_1160', 'd_1161', 'd_1162', 'd_1163', 'd_1164', 'd_1165', 'd_1166', 'd_1167', 'd_1168', 'd_1169', 'd_1170', 'd_1171', 'd_1172', 'd_1173', 'd_1174', 'd_1175', 'd_1176', 'd_1177', 'd_1178', 'd_1179', 'd_1180', 'd_1181', 'd_1182', 'd_1183', 'd_1184', 'd_1185', 'd_1186', 'd_1187', 'd_1188', 'd_1189', 'd_1190', 'd_1191', 'd_1192', 'd_1193', 'd_1194', 'd_1195', 'd_1196', 'd_1197', 'd_1198', 'd_1199', 'd_1200', 'd_1201', 'd_1202', 'd_1203', 'd_1204', 'd_1205', 'd_1206', 'd_1207', 'd_1208', 'd_1209', 'd_1210', 'd_1211', 'd_1212', 'd_1213', 'd_1214', 'd_1215', 'd_1216', 'd_1217', 'd_1218', 'd_1219', 'd_1220', 'd_1221', 'd_1222', 'd_1223', 'd_1224', 'd_1225', 'd_1226', 'd_1227', 'd_1228', 'd_1229', 'd_1230', 'd_1231', 'd_1232', 'd_1233', 'd_1234', 'd_1235', 'd_1236', 'd_1237', 'd_1238', 'd_1239', 'd_1240', 'd_1241', 'd_1242', 'd_1243', 'd_1244', 'd_1245', 'd_1246', 'd_1247', 'd_1248', 'd_1249', 'd_1250', 'd_1251', 'd_1252', 'd_1253', 'd_1254', 'd_1255', 'd_1256', 'd_1257', 'd_1258', 'd_1259', 'd_1260', 'd_1261', 'd_1262', 'd_1263', 'd_1264', 'd_1265', 'd_1266', 'd_1267', 'd_1268', 'd_1269', 'd_1270', 'd_1271', 'd_1272', 'd_1273', 'd_1274', 'd_1275', 'd_1276', 'd_1277', 'd_1278', 'd_1279', 'd_1280', 'd_1281', 'd_1282', 'd_1283', 'd_1284', 'd_1285', 'd_1286', 'd_1287', 'd_1288', 'd_1289', 'd_1290', 'd_1291', 'd_1292', 'd_1293', 'd_1294', 'd_1295', 'd_1296', 'd_1297', 'd_1298', 'd_1299', 'd_1300', 'd_1301', 'd_1302', 'd_1303', 'd_1304', 'd_1305', 'd_1306', 'd_1307', 'd_1308', 'd_1309', 'd_1310', 'd_1311', 'd_1312', 'd_1313', 'd_1314', 'd_1315', 'd_1316', 'd_1317', 'd_1318', 'd_1319', 'd_1320', 'd_1321', 'd_1322', 'd_1323', 'd_1324', 'd_1325', 'd_1326', 'd_1327', 'd_1328', 'd_1329', 'd_1330', 'd_1331', 'd_1332', 'd_1333', 'd_1334', 'd_1335', 'd_1336', 'd_1337', 'd_1338', 'd_1339', 'd_1340', 'd_1341', 'd_1342', 'd_1343', 'd_1344', 'd_1345', 'd_1346', 'd_1347', 'd_1348', 'd_1349', 'd_1350', 'd_1351', 'd_1352', 'd_1353', 'd_1354', 'd_1355', 'd_1356', 'd_1357', 'd_1358', 'd_1359', 'd_1360', 'd_1361', 'd_1362', 'd_1363', 'd_1364', 'd_1365', 'd_1366', 'd_1367', 'd_1368', 'd_1369', 'd_1370', 'd_1371', 'd_1372', 'd_1373', 'd_1374', 'd_1375', 'd_1376', 'd_1377', 'd_1378', 'd_1379', 'd_1380', 'd_1381', 'd_1382', 'd_1383', 'd_1384', 'd_1385', 'd_1386', 'd_1387', 'd_1388', 'd_1389', 'd_1390', 'd_1391', 'd_1392', 'd_1393', 'd_1394', 'd_1395', 'd_1396', 'd_1397', 'd_1398', 'd_1399', 'd_1400', 'd_1401', 'd_1402', 'd_1403', 'd_1404', 'd_1405', 'd_1406', 'd_1407', 'd_1408', 'd_1409', 'd_1410', 'd_1411', 'd_1412', 'd_1413', 'd_1414', 'd_1415', 'd_1416', 'd_1417', 'd_1418', 'd_1419', 'd_1420', 'd_1421', 'd_1422', 'd_1423', 'd_1424', 'd_1425', 'd_1426', 'd_1427', 'd_1428', 'd_1429', 'd_1430', 'd_1431', 'd_1432', 'd_1433', 'd_1434', 'd_1435', 'd_1436', 'd_1437', 'd_1438', 'd_1439', 'd_1440', 'd_1441', 'd_1442', 'd_1443', 'd_1444', 'd_1445', 'd_1446', 'd_1447', 'd_1448', 'd_1449', 'd_1450', 'd_1451', 'd_1452', 'd_1453', 'd_1454', 'd_1455', 'd_1456', 'd_1457', 'd_1458', 'd_1459', 'd_1460', 'd_1461', 'd_1462', 'd_1463', 'd_1464', 'd_1465', 'd_1466', 'd_1467', 'd_1468', 'd_1469', 'd_1470', 'd_1471', 'd_1472', 'd_1473', 'd_1474', 'd_1475', 'd_1476', 'd_1477', 'd_1478', 'd_1479', 'd_1480', 'd_1481', 'd_1482', 'd_1483', 'd_1484', 'd_1485', 'd_1486', 'd_1487', 'd_1488', 'd_1489', 'd_1490', 'd_1491', 'd_1492', 'd_1493', 'd_1494', 'd_1495', 'd_1496', 'd_1497', 'd_1498', 'd_1499', 'd_1500', 'd_1501', 'd_1502', 'd_1503', 'd_1504', 'd_1505', 'd_1506', 'd_1507', 'd_1508', 'd_1509', 'd_1510', 'd_1511', 'd_1512', 'd_1513', 'd_1514', 'd_1515', 'd_1516', 'd_1517', 'd_1518', 'd_1519', 'd_1520', 'd_1521', 'd_1522', 'd_1523', 'd_1524', 'd_1525', 'd_1526', 'd_1527', 'd_1528', 'd_1529', 'd_1530', 'd_1531', 'd_1532', 'd_1533', 'd_1534', 'd_1535', 'd_1536', 'd_1537', 'd_1538', 'd_1539', 'd_1540', 'd_1541', 'd_1542', 'd_1543', 'd_1544', 'd_1545', 'd_1546', 'd_1547', 'd_1548', 'd_1549', 'd_1550', 'd_1551', 'd_1552', 'd_1553', 'd_1554', 'd_1555', 'd_1556', 'd_1557', 'd_1558', 'd_1559', 'd_1560', 'd_1561', 'd_1562', 'd_1563', 'd_1564', 'd_1565', 'd_1566', 'd_1567', 'd_1568', 'd_1569', 'd_1570', 'd_1571', 'd_1572', 'd_1573', 'd_1574', 'd_1575', 'd_1576', 'd_1577', 'd_1578', 'd_1579', 'd_1580', 'd_1581', 'd_1582', 'd_1583', 'd_1584', 'd_1585', 'd_1586', 'd_1587', 'd_1588', 'd_1589', 'd_1590', 'd_1591', 'd_1592', 'd_1593', 'd_1594', 'd_1595', 'd_1596', 'd_1597', 'd_1598', 'd_1599', 'd_1600', 'd_1601', 'd_1602', 'd_1603', 'd_1604', 'd_1605', 'd_1606', 'd_1607', 'd_1608', 'd_1609', 'd_1610', 'd_1611', 'd_1612', 'd_1613', 'd_1614', 'd_1615', 'd_1616', 'd_1617', 'd_1618', 'd_1619', 'd_1620', 'd_1621', 'd_1622', 'd_1623', 'd_1624', 'd_1625', 'd_1626', 'd_1627', 'd_1628', 'd_1629', 'd_1630', 'd_1631', 'd_1632', 'd_1633', 'd_1634', 'd_1635', 'd_1636', 'd_1637', 'd_1638', 'd_1639', 'd_1640', 'd_1641', 'd_1642', 'd_1643', 'd_1644', 'd_1645', 'd_1646', 'd_1647', 'd_1648', 'd_1649', 'd_1650', 'd_1651', 'd_1652', 'd_1653', 'd_1654', 'd_1655', 'd_1656', 'd_1657', 'd_1658', 'd_1659', 'd_1660', 'd_1661', 'd_1662', 'd_1663', 'd_1664', 'd_1665', 'd_1666', 'd_1667', 'd_1668', 'd_1669', 'd_1670', 'd_1671', 'd_1672', 'd_1673', 'd_1674', 'd_1675', 'd_1676', 'd_1677', 'd_1678', 'd_1679', 'd_1680', 'd_1681', 'd_1682', 'd_1683', 'd_1684', 'd_1685', 'd_1686', 'd_1687', 'd_1688', 'd_1689', 'd_1690', 'd_1691', 'd_1692', 'd_1693', 'd_1694', 'd_1695', 'd_1696', 'd_1697', 'd_1698', 'd_1699', 'd_1700', 'd_1701', 'd_1702', 'd_1703', 'd_1704', 'd_1705', 'd_1706', 'd_1707', 'd_1708', 'd_1709', 'd_1710', 'd_1711', 'd_1712', 'd_1713', 'd_1714', 'd_1715', 'd_1716', 'd_1717', 'd_1718', 'd_1719', 'd_1720', 'd_1721', 'd_1722', 'd_1723', 'd_1724', 'd_1725', 'd_1726', 'd_1727', 'd_1728', 'd_1729', 'd_1730', 'd_1731', 'd_1732', 'd_1733', 'd_1734', 'd_1735', 'd_1736', 'd_1737', 'd_1738', 'd_1739', 'd_1740', 'd_1741', 'd_1742', 'd_1743', 'd_1744', 'd_1745', 'd_1746', 'd_1747', 'd_1748', 'd_1749', 'd_1750', 'd_1751', 'd_1752', 'd_1753', 'd_1754', 'd_1755', 'd_1756', 'd_1757', 'd_1758', 'd_1759', 'd_1760', 'd_1761', 'd_1762', 'd_1763', 'd_1764', 'd_1765', 'd_1766', 'd_1767', 'd_1768', 'd_1769', 'd_1770', 'd_1771', 'd_1772', 'd_1773', 'd_1774', 'd_1775', 'd_1776', 'd_1777', 'd_1778', 'd_1779', 'd_1780', 'd_1781', 'd_1782', 'd_1783', 'd_1784', 'd_1785', 'd_1786', 'd_1787', 'd_1788', 'd_1789', 'd_1790', 'd_1791', 'd_1792', 'd_1793', 'd_1794', 'd_1795', 'd_1796', 'd_1797', 'd_1798', 'd_1799', 'd_1800', 'd_1801', 'd_1802', 'd_1803', 'd_1804', 'd_1805', 'd_1806', 'd_1807', 'd_1808', 'd_1809', 'd_1810', 'd_1811', 'd_1812', 'd_1813', 'd_1814', 'd_1815', 'd_1816', 'd_1817', 'd_1818', 'd_1819', 'd_1820', 'd_1821', 'd_1822', 'd_1823', 'd_1824', 'd_1825', 'd_1826', 'd_1827', 'd_1828', 'd_1829', 'd_1830', 'd_1831', 'd_1832', 'd_1833', 'd_1834', 'd_1835', 'd_1836', 'd_1837', 'd_1838', 'd_1839', 'd_1840', 'd_1841', 'd_1842', 'd_1843', 'd_1844', 'd_1845', 'd_1846', 'd_1847', 'd_1848', 'd_1849', 'd_1850', 'd_1851', 'd_1852', 'd_1853', 'd_1854', 'd_1855', 'd_1856', 'd_1857', 'd_1858', 'd_1859', 'd_1860', 'd_1861', 'd_1862', 'd_1863', 'd_1864', 'd_1865', 'd_1866', 'd_1867', 'd_1868', 'd_1869', 'd_1870', 'd_1871', 'd_1872', 'd_1873', 'd_1874', 'd_1875', 'd_1876', 'd_1877', 'd_1878', 'd_1879', 'd_1880', 'd_1881', 'd_1882', 'd_1883', 'd_1884', 'd_1885', 'd_1886', 'd_1887', 'd_1888', 'd_1889', 'd_1890', 'd_1891', 'd_1892', 'd_1893', 'd_1894', 'd_1895', 'd_1896', 'd_1897', 'd_1898', 'd_1899', 'd_1900', 'd_1901', 'd_1902', 'd_1903', 'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913']

---------------- sales_evaluation ----------------
Number of Rows: 30490
Number of Columns: 1947
Columns

### Columns

In [5]:
# Inspect the first and last columns

for name, df in datasets.items():
    print(f"---------------- {name} ----------------")
    if len(df.columns) > 14:
        print("First 15 columns:")
        print(df.columns[:15])
        print("Last 10 columns:")
        print(df.columns[-15:])
    else:
        print("Columns")
        print(df.columns)
    print()

---------------- calendar ----------------
Columns
Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd',
       'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',
       'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='str')

---------------- sales_validation ----------------
First 15 columns:
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9'],
      dtype='str')
Last 10 columns:
Index(['d_1899', 'd_1900', 'd_1901', 'd_1902', 'd_1903', 'd_1904', 'd_1905',
       'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912',
       'd_1913'],
      dtype='str')

---------------- sales_evaluation ----------------
First 15 columns:
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9'],
      dtype='str')
Last 10 columns:
Index(['d_1927', 'd_1928', 'd_1929', 'd_1930', 'd_1931', 'd_1932', 'd_1933',
       'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938', 'd_1939', 'd_1940',
       'd_1941'],
      dtype='str')

---------------- sell_prices ----------------
Columns
Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='str')

In [6]:
# Verify that sales datasets contain 6 identifier columns followed by daily demand columns
sales_datasets = {
    "Sales Validation": sales_validation,
    "Sales Evaluation": sales_evaluation
}

for name, df in sales_datasets.items():
    daily_columns = df.columns[6:]
    print(f"---------------- {name} ----------------")    
    print(f"  Identifier columns: {len(df.columns[:6])}")
    print(f"  Daily demand columns: {len(daily_columns)}")
    print(f"  All daily columns start with 'd_': {all(col.startswith('d_') for col in daily_columns)}")
    print()

---------------- Sales Validation ----------------
  Identifier columns: 6
  Daily demand columns: 1913
  All daily columns start with 'd_': True

---------------- Sales Evaluation ----------------
  Identifier columns: 6
  Daily demand columns: 1941
  All daily columns start with 'd_': True

Both sales datasets have 6 identifier columns, followed by daily demand columns (d_). The evaluation dataset contains additional daily demand periods.

### Inspect First 5 Rows

In [7]:
for name, df in datasets.items():
    print(f"------------------ {name} ------------------")
    display(df.head())
    print()

------------------ calendar ------------------

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

------------------ sales_validation ------------------

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

------------------ sales_evaluation ------------------

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

------------------ sell_prices ------------------

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

### Inspect Last 5 Rows

In [8]:
for name, df in datasets.items():
    print(f"------------------ {name} ------------------")
    display(df.tail())
    print()

------------------ calendar ------------------

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
1964,2016-06-15,11620,Wednesday,5,6,2016,d_1965,NaN,NaN,NaN,NaN,0,1,1
1965,2016-06-16,11620,Thursday,6,6,2016,d_1966,NaN,NaN,NaN,NaN,0,0,0
1966,2016-06-17,11620,Friday,7,6,2016,d_1967,NaN,NaN,NaN,NaN,0,0,0
1967,2016-06-18,11621,Saturday,1,6,2016,d_1968,NaN,NaN,NaN,NaN,0,0,0
1968,2016-06-19,11621,Sunday,2,6,2016,d_1969,NBAFinalsEnd,Sporting,Father's day,Cultural,0,0,0

------------------ sales_validation ------------------

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
30485,FOODS_3_823_WI_3_validation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,2,0,0,0,0,0,1,0,0,1
30486,FOODS_3_824_WI_3_validation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
30487,FOODS_3_825_WI_3_validation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,2,1,0,2,0,1,0,0,1,0
30488,FOODS_3_826_WI_3_validation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,1,0,0,1,0,3,1,3
30489,FOODS_3_827_WI_3_validation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

------------------ sales_evaluation ------------------

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
30485,FOODS_3_823_WI_3_evaluation,FOODS_3_823,FOODS_3,FOODS,WI_3,WI,0,0,2,2,...,1,0,3,0,1,1,0,0,1,1
30486,FOODS_3_824_WI_3_evaluation,FOODS_3_824,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
30487,FOODS_3_825_WI_3_evaluation,FOODS_3_825,FOODS_3,FOODS,WI_3,WI,0,6,0,2,...,0,0,1,2,0,1,0,1,0,2
30488,FOODS_3_826_WI_3_evaluation,FOODS_3_826,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,1,1,4,6,0,1,1,1,0
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,0,0,0,0,...,1,2,0,5,4,0,2,2,5,1

------------------ sell_prices ------------------

        store_id      item_id  wm_yr_wk  sell_price
6841116     WI_3  FOODS_3_827     11617         1.0
6841117     WI_3  FOODS_3_827     11618         1.0
6841118     WI_3  FOODS_3_827     11619         1.0
6841119     WI_3  FOODS_3_827     11620         1.0
6841120     WI_3  FOODS_3_827     11621         1.0

## 3. Grain Identification

The dataset description provided by Kaggle defines the purpose of each file. 
Based on this description, the grain of each dataset was subjected for verification using the actual data.

In [9]:
# `calendar.csv` — Contains information about the dates on which the products are sold.

print("Rows:", len(calendar))
print("Unique dates:", calendar["date"].nunique())
print("Unique d values:", calendar["d"].nunique())
print("Unique calendar weeks:", calendar["wm_yr_wk"].nunique())

# Check whether one date maps to exactly one d value.
date_d_check = calendar.groupby("date")["d"].nunique()

print("\nDates mapped to more than one d value:",
      (date_d_check > 1).sum())

# Check whether one d value maps to exactly one date.
d_date_check = calendar.groupby("d")["date"].nunique()

print("d values mapped to more than one date:",
      (d_date_check > 1).sum())

Rows: 1969
Unique dates: 1969
Unique d values: 1969
Unique calendar weeks: 282

Dates mapped to more than one d value: 0
d values mapped to more than one date: 0

In [10]:
# `sales_train_validation.csv` 
# — Contains historical daily unit sales data per product and store (`d_1` to `d_1913`).

# Check whether each item-store combination appears only once.
item_store_counts_validation = (
    sales_validation
    .groupby(["item_id", "store_id"])
    .size()
)

print(
    "Duplicate item-store combinations:",
    (item_store_counts_validation > 1).sum()
)

Duplicate item-store combinations: 0

In [11]:
# `sales_train_evaluation.csv` — Contains sales through `d_1941`, including the additional evaluation period.

# Check whether each item-store combination appears only once.
item_store_counts_evaluation = (
    sales_evaluation
    .groupby(["item_id", "store_id"])
    .size()
)

print(
    "Duplicate item-store combinations:",
    (item_store_counts_evaluation > 1).sum()
)

Duplicate item-store combinations: 0

In [12]:
# `sell_prices.csv` — Contains information about the price of products sold per store and week.

print("Rows:", len(sell_prices))

# Count unique store-item-week combinations.
unique_price_combinations = (
    sell_prices[
        ["store_id", "item_id", "wm_yr_wk"]
    ]
    .drop_duplicates()
    .shape[0]
)

print(
    "Unique store-item-week combinations:",
    unique_price_combinations
)

print(
    "Duplicate store-item-week combinations:",
    len(sell_prices) - unique_price_combinations
)

Rows: 6841121
Unique store-item-week combinations: 6841121
Duplicate store-item-week combinations: 0

#### Grain Verified

| Dataset | Grain | Verification |
|---|---|---|
| `calendar.csv` | 1 row = 1 calendar date | Verified that each date is unique and maps to one `d` value |
| `sales_train_validation.csv` | 1 row = 1 product × store | Verified that each `item_id` × `store_id` combination is unique |
| `sales_train_evaluation.csv` | 1 row = 1 product × store | Verified that each `item_id` × `store_id` combination is unique |
| `sell_prices.csv` | 1 row = 1 product × store × week | Verified that each `item_id` × `store_id` × `wm_yr_wk` combination is unique |

## 4. Historical and Evaluation Period

In [3]:
print("Calendar start date:", calendar["date"].min())
print("Calendar end date:", calendar["date"].max())

Calendar start date: 2011-01-29
Calendar end date: 2016-06-19

In [4]:
historical_dates = calendar[
    calendar["d"].isin(
        [f"d_{i}" for i in range(1, 1914)]
    )
]

evaluation_dates = calendar[
    calendar["d"].isin(
        [f"d_{i}" for i in range(1914, 1942)]
    )
]

print("Historical period:",
      historical_dates["date"].min(),
      "to",
      historical_dates["date"].max())

print("Evaluation period:",
      evaluation_dates["date"].min(),
      "to",
      evaluation_dates["date"].max())

Historical period: 2011-01-29 to 2016-04-24
Evaluation period: 2016-04-25 to 2016-05-22

+ The historical sales data covers **January 29, 2011 to April 24, 2016**, corresponding to `d_1` through `d_1913`.

+ The evaluation period covers the following **28 days**, from **April 25, 2016 to May 22, 2016**, corresponding to `d_1914` through `d_1941`.

+ The calendar dataset contains additional dates beyond the evaluation period.

## 5. Data Quality Assessment

### 5.1 Data Types

In [14]:
# Calendar

calendar.dtypes

date              str
wm_yr_wk        int64
weekday           str
wday            int64
month           int64
year            int64
d                 str
event_name_1      str
event_type_1      str
event_name_2      str
event_type_2      str
snap_CA         int64
snap_TX         int64
snap_WI         int64
dtype: object

The `date` column in the calendar dataset is currently stored as a string (`object`). It will be converted to the `datetime` data type during the Data Cleaning stage to support date-based analysis and time-series operations.

In [15]:
# Sell Prices

sell_prices.dtypes

store_id          str
item_id           str
wm_yr_wk        int64
sell_price    float64
dtype: object

In [16]:
# Sales Validation & Sales Evaluation

for name, df in sales_datasets.items():

    print(f"============= {name} =============")
    print("---- Identifier Columns ----")
    print(df.iloc[:, :6].dtypes)
    print("---- Daily Demand Columns ----")
    print(df.iloc[:, 6:].dtypes.value_counts())
    print()

============= Sales Validation =============
---- Identifier Columns ----
id          str
item_id     str
dept_id     str
cat_id      str
store_id    str
state_id    str
dtype: object
---- Daily Demand Columns ----
int64    1913
Name: count, dtype: int64

============= Sales Evaluation =============
---- Identifier Columns ----
id          str
item_id     str
dept_id     str
cat_id      str
store_id    str
state_id    str
dtype: object
---- Daily Demand Columns ----
int64    1941
Name: count, dtype: int64

### 5.2 Missing Values

In [17]:
# Check missing values in each dataset
for name, df in datasets.items():
    print(f"------------------ {name} ------------------")
    print(df.isna().sum()[df.isna().sum() > 0])
    print()

------------------ calendar ------------------
event_name_1    1807
event_type_1    1807
event_name_2    1964
event_type_2    1964
dtype: int64

------------------ sales_validation ------------------
Series([], dtype: int64)

------------------ sales_evaluation ------------------
Series([], dtype: int64)

------------------ sell_prices ------------------
Series([], dtype: int64)

Missing values were found only in calendar event fields. These are expected because not every date has an associated event. No missing values were found in the sales or price datasets.

In [18]:
# Check whether related event name and event type fields are missing consistently
event_1_missing_match = (
    calendar["event_name_1"].isna() ==
    calendar["event_type_1"].isna()
).all()

event_2_missing_match = (
    calendar["event_name_2"].isna() ==
    calendar["event_type_2"].isna()
).all()

print("Event 1 missing values are consistent:", event_1_missing_match)
print("Event 2 missing values are consistent:", event_2_missing_match)

Event 1 missing values are consistent: True
Event 2 missing values are consistent: True

Missing values in the event fields are consistent. `event_name_1` and `event_type_1` are missing together, and `event_name_2` and `event_type_2` are missing together. This confirms that the missing values represent dates without associated events rather than incomplete event records.

### 5.3 Duplicate Rows

In [19]:
# Check duplicate rows in each dataset
for name, df in datasets.items():
    print(f"------------------ {name} ------------------")
    print(df.duplicated().sum())
    print()

------------------ calendar ------------------
0

------------------ sales_validation ------------------
0

------------------ sales_evaluation ------------------
0

------------------ sell_prices ------------------
0

No duplicate rows were found in any dataset.

### 5.4 Categorical Consistency & Format Standardization

#### 5.4.1 Calendar

In [20]:
for col in ["weekday", "wday", "month", "year"]:
    print(f"------------------ {col} ------------------")
    print(calendar[col].unique())
    print()

for col in ["event_name_1", "event_type_1", "event_name_2", "event_type_2"]:
    print(f"------------------ {col} ------------------")
    print(calendar[col].value_counts(dropna=False))
    print()

------------------ weekday ------------------
<StringArray>
['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
Length: 7, dtype: str

------------------ wday ------------------
[1 2 3 4 5 6 7]

------------------ month ------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]

------------------ year ------------------
[2011 2012 2013 2014 2015 2016]

------------------ event_name_1 ------------------
event_name_1
NaN                    1807
SuperBowl                 6
ValentinesDay             6
PresidentsDay             6
LentStart                 6
LentWeek2                 6
StPatricksDay             6
Purim End                 6
Pesach End                6
Mother's day              6
MemorialDay               6
NBAFinalsStart            6
NBAFinalsEnd              6
Ramadan starts            6
OrthodoxEaster            5
Cinco De Mayo             5
IndependenceDay           5
Eid al-Fitr               5
LaborDay                  5
ColumbusDay               5
Halloween                 5
EidAlAdha                 5
VeteransDay               5
Thanksgiving              5
Christmas                 5
Chanukah End              5
NewYear                   5
OrthodoxChristmas         5
MartinLutherKingDay       5
Easter                    5
Father's day              4
Name: count, dtype: int64

------------------ event_type_1 ------------------
event_type_1
NaN          1807
Religious      55
National       52
Cultural       37
Sporting       18
Name: count, dtype: int64

------------------ event_name_2 ------------------
event_name_2
NaN               1964
Father's day         2
Easter               1
Cinco De Mayo        1
OrthodoxEaster       1
Name: count, dtype: int64

------------------ event_type_2 ------------------
event_type_2
NaN          1964
Cultural        4
Religious       1
Name: count, dtype: int64

In [21]:
# Date Format check — YYYY-MM-DD

date_parts = calendar["date"].str.split("-", expand=True)

valid_date_format = (
    (date_parts[0].str.len() == 4) &
    (date_parts[0].str.isdigit()) &
    (date_parts[1].str.len() == 2) &
    (date_parts[1].str.isdigit()) &
    (date_parts[2].str.len() == 2) &
    (date_parts[2].str.isdigit())
)

print("Consistent date format:", valid_date_format.all())

Consistent date format: True

In [22]:
# Date consistency check

valid_dates = pd.to_datetime(calendar["date"], errors="coerce").notna()

print("Valid dates:", valid_dates.all())

Valid dates: True

In [23]:
# Check 'd' format

d_parts = calendar["d"].str.split("_", expand=True)

valid_d_format = (
    (d_parts.shape[1] == 2) &
    (d_parts[0] == "d") &
    (d_parts[1].str.isdigit())
)

print("Consistent d format:", valid_d_format.all())

Consistent d format: True

In [24]:
# Check 'd' sequence

expected_d = [f"d_{i}" for i in range(1, len(calendar) + 1)]

print("Sequential d values:", calendar["d"].tolist() == expected_d)

Sequential d values: True

Calendar fields follow the expected categories and formats. Dates are valid, and the d identifiers are correctly formatted, and sequential. No issues were identified.

#### 5.4.2 Sales Validation

In [25]:
for col in ["id", "item_id", "dept_id",	"cat_id", "store_id", "state_id"]:
    print(f"------------------ {col} ------------------")
    print(sales_validation[col].nunique())
    print()

------------------ id ------------------
30490

------------------ item_id ------------------
3049

------------------ dept_id ------------------
7

------------------ cat_id ------------------
3

------------------ store_id ------------------
10

------------------ state_id ------------------
3

In [26]:
# dept_id, cat_id, store_id, state_id

for col in ["dept_id",	"cat_id", "store_id", "state_id"]:
    print(f"------------------ {col} ------------------")
    print(sales_validation[col].value_counts())       
    print()

------------------ dept_id ------------------
dept_id
FOODS_3        8230
HOUSEHOLD_1    5320
HOUSEHOLD_2    5150
HOBBIES_1      4160
FOODS_2        3980
FOODS_1        2160
HOBBIES_2      1490
Name: count, dtype: int64

------------------ cat_id ------------------
cat_id
FOODS        14370
HOUSEHOLD    10470
HOBBIES       5650
Name: count, dtype: int64

------------------ store_id ------------------
store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: count, dtype: int64

------------------ state_id ------------------
state_id
CA    12196
TX     9147
WI     9147
Name: count, dtype: int64

In [27]:
# id

parts_sales_validation_id = sales_validation["id"].str.split("_", expand=True)

print("Number of parts in 'id' is 6:", (parts_sales_validation_id.shape[1] == 6), "\n")
print("Categories:", parts_sales_validation_id[0].unique(), "\n")
print("Department numbers:", parts_sales_validation_id[1].unique(), "\n")

print(
    "Item numbers:",
    ((parts_sales_validation_id[2].str.len() == 3) &
     (parts_sales_validation_id[2].str.isdigit())).all(),
    "\n"
)

print("States:", parts_sales_validation_id[3].unique(), "\n")
print("Store numbers:", parts_sales_validation_id[4].unique(), "\n")
print("Suffix:", parts_sales_validation_id[5].unique(), "\n")

Number of parts in 'id' is 6: True

Categories: <StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

Department numbers: <StringArray>
['1', '2', '3']
Length: 3, dtype: str

Item numbers: True

States: <StringArray>
['CA', 'TX', 'WI']
Length: 3, dtype: str

Store numbers: <StringArray>
['1', '2', '3', '4']
Length: 4, dtype: str

Suffix: <StringArray>
['validation']
Length: 1, dtype: str

In [28]:
# item_id

parts_sales_validation_item_id = sales_validation["item_id"].str.split("_", expand=True)

print("Number of parts in 'item_id' is 3:", (parts_sales_validation_item_id.shape[1] == 3), "\n")
print("Categories:", parts_sales_validation_item_id[0].unique(), "\n")
print("Department numbers:", parts_sales_validation_item_id[1].unique(), "\n")
print(
    "Item numbers:",
    ((parts_sales_validation_item_id[2].str.len() == 3) &
     (parts_sales_validation_item_id[2].str.isdigit())).all(),
    "\n"
)

Number of parts in 'item_id' is 3: True

Categories: <StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

Department numbers: <StringArray>
['1', '2', '3']
Length: 3, dtype: str

Item numbers: True

Sales Validation contains consistent department, category, store, and state identifiers. The id and item_id follow their expected structures, including valid category, department, state, store, and item-number components. No categorical or identifier-format inconsistencies were identified.

#### 5.4.3 Sales Evaluation

In [29]:
for col in ["id", "item_id", "dept_id",	"cat_id", "store_id", "state_id"]:
    print(f"------------------ {col} ------------------")
    print(sales_evaluation[col].nunique())
    print()

------------------ id ------------------
30490

------------------ item_id ------------------
3049

------------------ dept_id ------------------
7

------------------ cat_id ------------------
3

------------------ store_id ------------------
10

------------------ state_id ------------------
3

In [30]:
# dept_id, cat_id, store_id, state_id

for col in ["dept_id",	"cat_id", "store_id", "state_id"]:
    print(f"------------------ {col} ------------------")
    print(sales_evaluation[col].value_counts())       
    print()

------------------ dept_id ------------------
dept_id
FOODS_3        8230
HOUSEHOLD_1    5320
HOUSEHOLD_2    5150
HOBBIES_1      4160
FOODS_2        3980
FOODS_1        2160
HOBBIES_2      1490
Name: count, dtype: int64

------------------ cat_id ------------------
cat_id
FOODS        14370
HOUSEHOLD    10470
HOBBIES       5650
Name: count, dtype: int64

------------------ store_id ------------------
store_id
CA_1    3049
CA_2    3049
CA_3    3049
CA_4    3049
TX_1    3049
TX_2    3049
TX_3    3049
WI_1    3049
WI_2    3049
WI_3    3049
Name: count, dtype: int64

------------------ state_id ------------------
state_id
CA    12196
TX     9147
WI     9147
Name: count, dtype: int64

In [31]:
# id

parts_sales_evaluation_id = sales_evaluation["id"].str.split("_", expand=True)

print("Number of parts in 'id' is 6:", (parts_sales_evaluation_id.shape[1] == 6), "\n")
print("Categories:", parts_sales_evaluation_id[0].unique(), "\n")
print("Department numbers:", parts_sales_evaluation_id[1].unique(), "\n")

print(
    "Item numbers:",
    ((parts_sales_evaluation_id[2].str.len() == 3) &
     (parts_sales_evaluation_id[2].str.isdigit())).all(),
    "\n"
)

print("States:", parts_sales_evaluation_id[3].unique(), "\n")
print("Store numbers:", parts_sales_evaluation_id[4].unique(), "\n")
print("Suffix:", parts_sales_evaluation_id[5].unique(), "\n")

Number of parts in 'id' is 6: True

Categories: <StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

Department numbers: <StringArray>
['1', '2', '3']
Length: 3, dtype: str

Item numbers: True

States: <StringArray>
['CA', 'TX', 'WI']
Length: 3, dtype: str

Store numbers: <StringArray>
['1', '2', '3', '4']
Length: 4, dtype: str

Suffix: <StringArray>
['evaluation']
Length: 1, dtype: str

In [32]:
# item_id

parts_sales_evaluation_item_id = sales_evaluation["item_id"].str.split("_", expand=True)

print("Number of parts in 'item_id' is 3:", (parts_sales_evaluation_item_id.shape[1] == 3), "\n")
print("Categories:", parts_sales_evaluation_item_id[0].unique(), "\n")
print("Department numbers:", parts_sales_evaluation_item_id[1].unique(), "\n")
print(
    "Item numbers:",
    ((parts_sales_evaluation_item_id[2].str.len() == 3) &
     (parts_sales_evaluation_item_id[2].str.isdigit())).all(),
    "\n"
)

Number of parts in 'item_id' is 3: True

Categories: <StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

Department numbers: <StringArray>
['1', '2', '3']
Length: 3, dtype: str

Item numbers: True

Sales Evaluation contains consistent department, category, store, and state identifiers. The id and item_id follow their expected structures, including valid category, department, state, store, and item-number components. No categorical or identifier-format inconsistencies were identified.

#### 5.4.4 Sell Prices

In [33]:
for col in ["store_id", "item_id"]:
    print(f"------------------ {col} ------------------")
    print(sell_prices[col].nunique())
    print()

------------------ store_id ------------------
10

------------------ item_id ------------------
3049

In [34]:
# store_id

sell_prices["store_id"].value_counts()

store_id
TX_2    701214
TX_1    699796
CA_1    698412
WI_3    696094
CA_3    693990
TX_3    691112
CA_4    679025
WI_2    678171
WI_1    665912
CA_2    637395
Name: count, dtype: int64

In [35]:
# item_id

parts_sell_prices_item_id = sell_prices["item_id"].str.split("_", expand=True)

print("Number of parts in 'item_id' is 3:", (parts_sell_prices_item_id.shape[1] == 3), "\n")
print("Categories:", parts_sell_prices_item_id[0].unique(), "\n")
print("Department numbers:", parts_sell_prices_item_id[1].unique(), "\n")
print(
    "Item numbers:",
    ((parts_sell_prices_item_id[2].str.len() == 3) &
     (parts_sell_prices_item_id[2].str.isdigit())).all(),
    "\n"
)

Number of parts in 'item_id' is 3: True

Categories: <StringArray>
['HOBBIES', 'HOUSEHOLD', 'FOODS']
Length: 3, dtype: str

Department numbers: <StringArray>
['1', '2', '3']
Length: 3, dtype: str

Item numbers: True

The store_id and item_id values are consistent. The item_id values follow the expected three-part structure, with valid category, department, and three-digit item components. No identifier-format inconsistencies were identified.

### 5.5 Numeric Range Validation

#### 5.5.1 Calendar

In [36]:
# wm_yr_wk

valid_wm_yr_wk_calendar = (
    (calendar["wm_yr_wk"] > 0) &
    (calendar["wm_yr_wk"].astype(str).str.len() == 5)
)

print("Valid wm_yr_wk:", valid_wm_yr_wk_calendar.all())

Valid wm_yr_wk: True

In [37]:
# snap_CA, snap_TX, snap_WI

for col in ["snap_CA", "snap_TX", "snap_WI"]:
    print(f"------------------ {col} ------------------")
    print(calendar[col].unique())
    print()

------------------ snap_CA ------------------
[0 1]

------------------ snap_TX ------------------
[0 1]

------------------ snap_WI ------------------
[0 1]

+ wm_yr_wk values are valid, positive, and consistently follow the expected 5-digit format.
+ snap_CA, snap_TX, and snap_WI contain only the expected binary values (0 and 1).
+ No numeric range or format issues were identified in these calendar fields.

#### 5.5.2 Sales Validation & Sales Validation

In [38]:
# 'd_1' to 'd_1913'

sales_validation_demand = sales_validation.iloc[:, 6:]

print(
    "Sales Validation has no negative demand:",
    (sales_validation_demand >= 0).all().all()
)

Sales Validation has no negative demand: True

In [39]:
# 'd_1' to 'd_1941'

sales_evaluation_demand = sales_evaluation.iloc[:, 6:]

print(
    "Sales Evaluation has no negative demand:",
    (sales_evaluation_demand >= 0).all().all()
)

Sales Evaluation has no negative demand: True

Daily sales values are non-negative, with zero representing no units sold. No invalid negative demand values were identified.

#### 5.5.3 Sell Prices

In [ ]:
# wm_yr_wk

valid_wm_yr_wk_sell_prices = (
    (sell_prices["wm_yr_wk"] > 0) &
    (sell_prices["wm_yr_wk"].astype(str).str.len() == 5)
)

print("Valid wm_yr_wk:", valid_wm_yr_wk_sell_prices.all())

In [ ]:
# sell_price

print(
    "All sell prices are positive:",
    (sell_prices["sell_price"] > 0).all()
)

All sell prices are positive: True

+ wm_yr_wk values are valid, positive, and consistently follow the expected 5-digit format.
+ All sell prices are positive. No zero or negative price values were identified.

### 5.6 Logical Consistency

#### 5.6.1 Calendar

In [ ]:
# Validate calendar fields against date

date_check = pd.to_datetime(calendar["date"])

valid_weekday = date_check.dt.day_name() == calendar["weekday"]
valid_wday = date_check.dt.dayofweek + 1 == calendar["wday"]
valid_month = date_check.dt.month == calendar["month"]
valid_year = date_check.dt.year == calendar["year"]

print("Weekday consistency:", valid_weekday.all())
print("Wday consistency:", valid_wday.all())
print("Month consistency:", valid_month.all())
print("Year consistency:", valid_year.all())

Weekday consistency: True
Wday consistency: False
Month consistency: True
Year consistency: True

In [ ]:
wday_mapping = {
    "Saturday": 1,
    "Sunday": 2,
    "Monday": 3,
    "Tuesday": 4,
    "Wednesday": 5,
    "Thursday": 6,
    "Friday": 7
}

expected_wday = calendar["weekday"].map(wday_mapping)

print(
    "Wday consistency:",
    (expected_wday == calendar["wday"]).all()
)

Wday consistency: True

+ The weekday, wday, month, and year fields are logically consistent with the corresponding date values. 
+ The wday field follows the dataset's convention of Saturday = 1 through Friday = 7. 
+ No inconsistencies were identified.

#### 5.6.2 Sales Validation & Sales Evaluation

##### cat_id ↔ dept_id

In [ ]:
# Checks department belongs to the correct category

expected_dept_category = {
    "FOODS_1": "FOODS",
    "FOODS_2": "FOODS",
    "FOODS_3": "FOODS",
    "HOBBIES_1": "HOBBIES",
    "HOBBIES_2": "HOBBIES",
    "HOUSEHOLD_1": "HOUSEHOLD",
    "HOUSEHOLD_2": "HOUSEHOLD"
}

for name, df in sales_datasets.items():
    check = df["dept_id"].map(expected_dept_category).eq(df["cat_id"]).all()
    print(f"{name} - Department/Category consistency:", check)

Sales Validation - Department/Category consistency: True
Sales Evaluation - Department/Category consistency: True

##### state_id ↔ store_id

In [ ]:
# Checks store belongs to the correct state

for name, df in sales_datasets.items():
    check = (
        df.groupby("store_id")["state_id"]
        .nunique()
        .eq(1)
        .all()
    )

    print(f"{name} - Store/State consistency:", check)

Sales Validation - Store/State consistency: True
Sales Evaluation - Store/State consistency: True

##### item_id ↔ dept_id

In [ ]:
# Checks product belongs to the correct department

for name, df in sales_datasets.items():
    item_dept_check = (
        df.groupby("item_id")["dept_id"]
        .nunique()
        .eq(1)
        .all()
    )

    print(f"{name} - Item/Department consistency:", item_dept_check)

Sales Validation - Item/Department consistency: True
Sales Evaluation - Item/Department consistency: True

##### id ↔ item_id + store_id

In [ ]:
# Checks ID correctly represents the product-store combination

for name, df in sales_datasets.items():
    suffix = df["id"].str.rsplit("_", n=1).str[-1]

    expected_id = (
        df["item_id"]
        + "_"
        + df["store_id"]
        + "_"
        + suffix
    )

    check = df["id"].eq(expected_id).all()

    print(f"{name} - ID consistency:", check)

Sales Validation - ID consistency: True
Sales Evaluation - ID consistency: True

The relationships between the sales dataset fields are logically consistent. Each department maps correctly to its category, each store maps consistently to its state, each product maps consistently to its department, and the `id` correctly represents the corresponding product-store combination. No logical inconsistencies were identified.

### 5.7 Referential Integrity

In [ ]:
# Check whether sell_prices store IDs exist in the sales dataset
store_check = sell_prices["store_id"].isin(
    sales_validation["store_id"]
)

# Check whether sell_prices item IDs exist in the sales dataset
item_check = sell_prices["item_id"].isin(
    sales_validation["item_id"]
)

# Check whether sell_prices week IDs exist in the calendar dataset
week_check = sell_prices["wm_yr_wk"].isin(
    calendar["wm_yr_wk"]
)

print("Store ID referential integrity:", store_check.all())
print("Item ID referential integrity:", item_check.all())
print("WM Year-Week referential integrity:", week_check.all())

Store ID referential integrity: True
Item ID referential integrity: True
WM Year-Week referential integrity: True

All `store_id`, `item_id`, and `wm_yr_wk` values in `sell_prices` have corresponding values in the related sales and calendar datasets. No referential integrity issues were identified.

### 5.8 Cross-Dataset Consistency

##### Validation and Evaluation Dataset Consistency

In [ ]:
# Compare the common historical data between the validation and evaluation datasets

common_columns = sales_validation.columns

identifier_columns = [
    "item_id", "dept_id", "cat_id", "store_id", "state_id"
]

identifier_match = all(
    sales_validation[col].reset_index(drop=True).equals(
        sales_evaluation[col].reset_index(drop=True)
    )
    for col in identifier_columns
)

historical_demand_match = (
    sales_validation[common_columns[6:]]
    .reset_index(drop=True)
    .equals(
        sales_evaluation[common_columns[6:]]
        .reset_index(drop=True)
    )
)

print("Identifier consistency:", identifier_match)
print("Historical demand consistency:", historical_demand_match)

Identifier consistency: True
Historical demand consistency: True

The shared identifiers and historical demand (d_1 to d_1913) are consistent between the validation and evaluation datasets. The id field was excluded because its suffix differs by dataset (_validation vs _evaluation). No inconsistencies were identified in the shared historical data.

In [ ]:
# Compare IDs after removing the dataset-specific suffix

validation_id = sales_validation["id"].str.rsplit("_", n=1).str[0]
evaluation_id = sales_evaluation["id"].str.rsplit("_", n=1).str[0]

print(
    "ID consistency:",
    validation_id.reset_index(drop=True).equals(
        evaluation_id.reset_index(drop=True)
    )
)

ID consistency: True

The `id` values in the validation and evaluation datasets represent the same product-store combinations after removing their dataset-specific suffixes. No inconsistencies were identified.

##### Calendar and Sales Day Identifier Consistency

In [ ]:
# Check that validation sales day identifiers match the corresponding calendar d values
validation_d_columns = sales_validation.columns[6:]
calendar_d_values = calendar["d"].iloc[:len(validation_d_columns)]

print(
    "Calendar and evaluation day identifiers match:",
    validation_d_columns.tolist() == calendar_d_values.tolist()
)

Calendar and evaluation day identifiers match: True

In [ ]:
# Check that evaluation sales day identifiers match the corresponding calendar d values
evaluation_d_columns = sales_evaluation.columns[6:]
calendar_d_values = calendar["d"].iloc[:len(evaluation_d_columns)]

print(
    "Calendar and evaluation day identifiers match:",
    evaluation_d_columns.tolist() == calendar_d_values.tolist()
)

Calendar and evaluation day identifiers match: True

The daily sales identifiers in both the validation and evaluation datasets correctly align with the corresponding `d` values in the calendar dataset. This ensures that the sales data can be mapped correctly to the corresponding calendar dates.

### 5.9 Temporal Consistency

In [ ]:
# Convert dates temporarily for temporal consistency checks
date_check = pd.to_datetime(calendar["date"])

# Check chronological order
print(
    "Dates are chronological:",
    date_check.is_monotonic_increasing
)

# Check for consecutive daily dates
date_difference = date_check.diff().dropna()

print(
    "No unexpected gaps between dates:",
    (date_difference == pd.Timedelta(days=1)).all()
)

# Check that the date range is continuous
print(
    "Continuous date range:",
    len(date_check) == (date_check.max() - date_check.min()).days + 1
)

Dates are chronological: True
No unexpected gaps between dates: True
Continuous date range: True

The calendar dates are in chronological order and form a continuous daily sequence without unexpected gaps. The date range is complete for the period covered by the dataset.

### 5.10 Outliers / Anomalies

#### Sales demand

In [ ]:
# Identify unusually high demand values using the IQR method
for name, df in sales_datasets.items():
    demand = df.iloc[:, 6:]

    Q1 = demand.stack().quantile(0.25)
    Q3 = demand.stack().quantile(0.75)
    IQR = Q3 - Q1

    upper_limit = Q3 + 1.5 * IQR

    outlier_count = (demand > upper_limit).sum().sum()

    print(f"{name} - Upper outlier limit:", upper_limit)
    print(f"{name} - Number of high-demand observations:", outlier_count)

Sales Validation - Upper outlier limit: 2.5
Sales Validation - Number of high-demand observations: 6902589
Sales Evaluation - Upper outlier limit: 2.5
Sales Evaluation - Number of high-demand observations: 7037502

Sales demand contains a large number of zero and low-volume observations, making a global IQR-based outlier threshold unsuitable.

In [ ]:
# Extreme Value Check
# Check the maximum daily sales value in each sales dataset to identify the highest observed demand.

for name, df in sales_datasets.items():
    demand = df.iloc[:, 6:]
    max_sales = demand.max().max()

    print(f"{name} - Maximum daily sales:", max_sales)

Sales Validation - Maximum daily sales: 763
Sales Evaluation - Maximum daily sales: 763

The maximum daily sales value is 763 units in both the validation and evaluation datasets. This value is retained because a high demand value is not necessarily a data-quality issue.

#### Selling Price

In [ ]:
# Use the Interquartile Range (IQR) method to identify unusually high or low selling prices.

Q1 = sell_prices["sell_price"].quantile(0.25)
Q3 = sell_prices["sell_price"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = sell_prices[
    (sell_prices["sell_price"] < lower_limit) |
    (sell_prices["sell_price"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Number of potential price outliers:", len(outliers))

Q1: 2.18
Q3: 5.84
IQR: 3.6599999999999997
Lower limit: -3.309999999999999
Upper limit: 11.329999999999998
Number of potential price outliers: 303640

The IQR method identified 303,640 selling-price observations above the upper statistical limit of $11.33.

In [ ]:
# Minimum and Maximum Selling Price

print("Minimum selling price:", sell_prices["sell_price"].min())
print("Maximum selling price:", sell_prices["sell_price"].max())

Minimum selling price: 0.01
Maximum selling price: 107.32

Selling prices range from $0.01 to $107.32. The IQR method identified prices above $11.33 as potential statistical outliers. These observations were retained because extreme prices may represent legitimate product pricing rather than data-quality errors.

## Data Quality Assessment Summary

| Check | Result | Finding / Action |
|---|---|---|
| Duplicate grain keys | Pass | No duplicate records were found at the defined dataset grains. |
| Data types | Review | `calendar.date` is stored as string and will be converted to datetime during cleaning. Other data types are appropriate. |
| Missing values | Review | Missing values found only in calendar event fields; Event-field missing values are consistent and represent dates without associated events. |
| Duplicate rows | Pass | No duplicate rows found in any dataset. |
| Allowed values | Pass | Categorical and indicator fields contain expected values. |
| Format consistency | Pass | Dates, identifiers, and categorical formats follow expected structures. |
| Range checks | Pass | Demand is non-negative, SNAP indicators are binary, and selling prices are positive. |
| Logical consistency | Pass | Related fields such as category/department and store/state are consistent; `wday` follows the dataset convention of Saturday = 1 through Friday = 7.|
| Referential integrity | Pass | Required keys exist across related datasets. |
| Cross-dataset consistency | Pass | Historical sales, and calendar-day mappings are consistent across datasets. |
| Temporal consistency | Pass | Calendar dates form a continuous chronological sequence. |
| Outliers / anomalies | Review | Extreme demand and price values were identified for review but were not automatically treated as errors. |

## 6. Data Cleaning

The raw datasets are treated as immutable source data and will not be modified. All cleaning operations are performed on the loaded DataFrames, and the cleaned datasets will be saved separately in the `data/processed/cleaned/` directory.

### Convert Date to Datetime

The `calendar.date` column is currently stored as a string. Since the project involves time-series analysis, the column will be converted to the datetime data type.

In [ ]:
calendar["date"] = pd.to_datetime(calendar["date"])

### Calendar Event Missing Values

Missing values were identified in the calendar event fields: `event_name_1`, `event_type_1`, `event_name_2`, and `event_type_2`.

These missing values represent dates without associated events and are therefore treated as expected structural missing values. No imputation or row removal is required.

### Outliers / Anomalies

#### Sales Demand Extreme-Value Check

The maximum daily sales value was reviewed to identify potentially extreme demand observations.

The maximum observed demand was 763 units in both the validation and evaluation datasets. The value was retained because an unusually high demand value is not necessarily a data-quality error.

#### Selling Price Outlier Check

The IQR method was used to identify statistically unusual selling prices.

The upper IQR limit was $11.33, resulting in 303,640 potential statistical outliers. The observed selling price range was $0.01 to $107.32.

These observations were retained because statistical outliers are not necessarily data-quality errors and may represent legitimate differences in product pricing.

## Data Cleaning Summary

| Issue Identified | Finding | Cleaning Action |
|---|---|---|
| `calendar.date` data type | Stored as string | Converted to datetime |
| Calendar event missing values | Missing values represent dates without associated events | Retained as-is; no imputation required |
| Sales extreme demand | Maximum daily sales = 763 units | Retained as-is; no evidence of a data error |
| Selling-price outliers | 303,640 statistical outliers identified by IQR | Retained as-is; statistical outliers are not necessarily invalid prices |

## 7. Data Validation after Cleaning

In [ ]:
# Validate Data type of Date 

print(calendar["date"].dtype)

datetime64[us]

The `calendar.date` column was successfully converted from string to datetime, making it suitable for date-based and time-series analysis.

+ The cleaning process involved only converting `calendar.date` from string to datetime. The conversion was validated successfully, with no invalid or missing dates introduced.

+ No additional validation was required because no other data values, records, or structures were modified during cleaning.

In [ ]:
calendar.to_csv(
    "../data/processed/cleaned/calendar.csv",
    index=False
)

## 8. Data Transformation

Data transformation is performed only when the current data structure is not convenient for the planned analysis.

The validation and evaluation sales datasets store daily demand across separate columns (`d_1`, `d_2`, ...). This wide format is inconvenient for time-based analysis and forecasting. Therefore, the daily demand columns will be reshaped into a long format with one row per product, store, and day.

The calendar and selling-price datasets will remain as separate tables because their existing structures are suitable for analysis and can be joined when required.

#### Transform Validation Sales from Wide to Long

In [ ]:
# Reshape historical sales

id_columns = [
    "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id"
]

demand_columns = sales_validation.columns[6:]

sales_historical = sales_validation.melt(
    id_vars=id_columns,
    value_vars=demand_columns,
    var_name="d",
    value_name="demand"
)

##### Historical Sales Validation after Transformation

In [ ]:
print(sales_historical.shape)
print(sales_historical.columns.tolist())
sales_historical.head()

(58327370, 8)
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd', 'demand']

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0

In [ ]:
print(
    "Duplicate product-store-day records:",
    sales_historical.duplicated(
        subset=["item_id", "store_id", "d"]
    ).sum()
)

print(
    "First day:",
    sales_historical["d"].min()
)

print(
    "Last day:",
    sales_historical["d"].max()
)

print(
    "Expected rows:",
    len(sales_validation) * len(demand_columns)
)

print(
    "Actual rows:",
    len(sales_historical)
)

Duplicate product-store-day records: 0
First day: d_1
Last day: d_999
Expected rows: 58327370
Actual rows: 58327370

d_999 is not the last day. This is a lexicographic string-order issue: for strings, d_999 sorts after d_1913, even though numerically 999 < 1913

In [ ]:
# Verify the actual d range numerically

d_numbers = sales_historical["d"].str.replace("d_", "").astype(int)

print("First day:", d_numbers.min())
print("Last day:", d_numbers.max())
print("Number of unique days:", d_numbers.nunique())

First day: 1
Last day: 1913
Number of unique days: 1913

In [ ]:
print("Original product-store records:", len(sales_validation))
print(
    "Transformed product-store records:",
    sales_historical[["item_id", "store_id"]].drop_duplicates().shape[0]
)

print(
    "Original total demand:",
    sales_validation.iloc[:, 6:].sum().sum()
)

print(
    "Transformed total demand:",
    sales_historical["demand"].sum()
)

print(
    "Same item-store combinations:",
    sales_historical[["item_id", "store_id"]].drop_duplicates().shape[0]
    == sales_validation[["item_id", "store_id"]].drop_duplicates().shape[0]
)

print(
    "Same total demand:",
    sales_historical["demand"].sum()
    == sales_validation.iloc[:, 6:].sum().sum()
)

Original product-store records: 30490
Transformed product-store records: 30490
Original total demand: 65695409
Transformed total demand: 65695409
Same item-store combinations: True
Same total demand: True

In [ ]:
print(
    "Total missing values:",
    sales_historical.isna().sum().sum()
)

Total missing values: 0

In [ ]:
print(
    "Total exact duplicate rows:",
    sales_historical.duplicated().sum()
)

Total exact duplicate rows: 0

The wide-to-long transformation preserved the original validation sales data. The transformed dataset contains the expected 58,327,370 rows, representing 30,490 product-store combinations across 1,913 days.

No product-store-day duplicates or exact duplicate rows were created during the transformation. No missing values were introduced, and the total demand remained unchanged at 65,695,409 units.

The transformed data therefore preserves the original records and demand values while converting the dataset into a long format suitable for time-based demand analysis.

#### Transform Evaluation Sales from Wide to Long

The evaluation dataset contains both historical demand (`d_1` to `d_1913`) and the additional evaluation period (`d_1914` to `d_1941`).

Only the evaluation period will be reshaped into long format because the historical period has already been transformed into `sales_historical`.

In [ ]:
evaluation_demand_columns = [
    col for col in sales_evaluation.columns
    if col.startswith("d_") and 1914 <= int(col.split("_")[1]) <= 1941
]

sales_evaluation_long = sales_evaluation.melt(
    id_vars=id_columns,
    value_vars=evaluation_demand_columns,
    var_name="d",
    value_name="demand"
)

##### Evaluation Long Sales Validation after Transformation

In [ ]:
print(sales_evaluation_long.shape)
print(sales_evaluation_long.columns.tolist())
sales_evaluation_long.head()

(853720, 8)
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd', 'demand']

,id,item_id,dept_id,cat_id,store_id,state_id,d,demand
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1914,0
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,d_1914,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,d_1914,0
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,d_1914,0
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,d_1914,1

In [ ]:
print(
    "First day:",
    sales_evaluation_long["d"]
    .str.replace("d_", "")
    .astype(int)
    .min()
)

print(
    "Last day:",
    sales_evaluation_long["d"]
    .str.replace("d_", "")
    .astype(int)
    .max()
)

print(
    "Number of unique days:",
    sales_evaluation_long["d"].nunique()
)

print(
    "Expected rows:",
    len(sales_evaluation) * len(evaluation_demand_columns)
)

print(
    "Actual rows:",
    len(sales_evaluation_long)
)

First day: 1914
Last day: 1941
Number of unique days: 28
Expected rows: 853720
Actual rows: 853720

In [ ]:
print(
    "Total missing values:",
    sales_evaluation_long.isna().sum().sum()
)

print(
    "Total exact duplicate rows:",
    sales_evaluation_long.duplicated().sum()
)

print(
    "Duplicate product-store-day records:",
    sales_evaluation_long.duplicated(
        subset=["item_id", "store_id", "d"]
    ).sum()
)

Total missing values: 0
Total exact duplicate rows: 0
Duplicate product-store-day records: 0

In [ ]:
print(
    "Original product-store records:",
    len(sales_evaluation)
)

print(
    "Transformed product-store records:",
    sales_evaluation_long[
        ["item_id", "store_id"]
    ].drop_duplicates().shape[0]
)

print(
    "Same item-store combinations:",
    sales_evaluation_long[
        ["item_id", "store_id"]
    ].drop_duplicates().shape[0]
    == sales_evaluation[
        ["item_id", "store_id"]
    ].drop_duplicates().shape[0]
)

Original product-store records: 30490
Transformed product-store records: 30490
Same item-store combinations: True

In [ ]:
original_evaluation_demand = sales_evaluation[
    evaluation_demand_columns
].sum().sum()

transformed_evaluation_demand = sales_evaluation_long[
    "demand"
].sum()

print("Original evaluation-period demand:", original_evaluation_demand)
print("Transformed evaluation-period demand:", transformed_evaluation_demand)

print(
    "Same evaluation-period demand:",
    original_evaluation_demand == transformed_evaluation_demand
)

Original evaluation-period demand: 1231764
Transformed evaluation-period demand: 1231764
Same evaluation-period demand: True

The evaluation sales data was successfully transformed from wide to long format for the evaluation period (`d_1914` to `d_1941`).

The transformation preserved all 30,490 product-store combinations and the total demand for the evaluation period. No missing values, exact duplicate rows, or duplicate product-store-day records were introduced.

The transformed data is therefore ready to be saved as the evaluation sales dataset.

In [ ]:
# Save historical sales

sales_historical.to_csv(
    "../data/processed/analytical/sales_historical.csv",
    index=False
)

In [ ]:
# Save evaluation sales

sales_evaluation_long.to_csv(
    "../data/processed/analytical/sales_evaluation.csv",
    index=False
)

## Data Transformation Summary

| Dataset | Transformation | Result |
|---|---|---|
| Validation Sales | Wide → Long (`d_1`–`d_1913`) | `sales_historical.csv` |
| Evaluation Sales | Wide → Long (`d_1914`–`d_1941`) | `sales_evaluation.csv` |
| Calendar | No structural transformation | Retained as a separate table |
| Selling Prices | No structural transformation | Retained as a separate table |

The sales datasets were reshaped to support time-based demand analysis and forecasting while keeping calendar and selling-price data as separate tables. The transformations were validated to ensure that the original records and demand values were preserved.